export const ANIMATION_DURATION = {
    HINT_REVEAL: 0.5,
    ROW_APPEAR: 0.4,
    END_SCREEN_TRANSITION: 0.7,
    KEY_HOVER: 0.2,
    LINK_HOVER: 0.2,
    MESSAGE_TRANSITION: 0.5,
    MESSAGE_HIDE_DELAY: 2
}